### ISSUE TITLE
version 1.0.2

### ISSUE THREAD

**Issue by SingingBush** [robik/ConsoleD#30]
any chance of tagging a new version so that I can get the OSX fix via the dub repo

**Comment by vladdeSV** [comment]
New tag added (thanks @adamdruppe), just wait for dub to update

**Comment by adamdruppe** [comment]
On Fri, Jul 01, 2016 at 03:55:24PM -0700, Samael wrote:
> any chance of tagging a new version so that I can get the OSX fix via the dub repo

try it now

**Comment by SingingBush** [comment]
wow, that was quick. I thought this fix was pulled in (https://github.com/robik/ConsoleD/issues/19) unfortunately I'm still getting same error:

```
../../../.dub/packages/consoled-1.0.2/consoled/source/consoled.d(766,30): Error: undefined identifier 'TIOCGWINSZ'
```

**Comment by adamdruppe** [comment]
On Fri, Jul 01, 2016 at 04:35:25PM -0700, Samael wrote:
> ../../../.dub/packages/consoled-1.0.2/consoled/source/consoled.d(766,30): Error: undefined identifier 'TIOCGWINSZ'

oh, consoled.d and terminal.d are separate (they are just together because
we borrowed a bit of each other's code)... the same change probably needs
to be made in consoled.

**Comment by vladdeSV** [comment]
@adamdruppe... both v1.0.2 have the same commit id 744a9f382e3c27165dfeb5fffcf92029668639f7
I suspect you didn't `git pull` before making that tag.

**Comment by adamdruppe** [comment]
On Fri, Jul 01, 2016 at 04:51:42PM -0700, Vladde Nordholm wrote:
> @adamdruppe... both v1.0.2 have the same commit id 744a9f382e3c27165dfeb5fffcf92029668639f7
> I suspect you didn't `git pull` before making that tag.

argh i told you i didn't know how!

whelp try it again now

**Comment by SingingBush** [comment]
dub can't find the new tag yet. I'll try again tomorrow. 

It's probably worth setting up a travis build for the project to ensure that it can work with the various compiler / os combinations. The following `.travis.yml` in the root of the project will do:

```yaml
# travis-ci.org supports D, using dub with various compilers
language: d

sudo: required
dist: trusty

d:
  - dmd
  - dmd-2.069.2
  - ldc
  - gdc

os:
 - linux
 - osx

script: dub build

# GDC lags behind DMD
matrix:
  allow_failures:
    - d: gdc
```
